Update spotify.snap to 1.2.22.982.g794acc0a
flathub/com.spotify.Client pull request #260
Opened 2023-10-22 08:19 UTC by slagiewka

2023-10-22 08:36 UTC, slagiewka commented
One thing that is not great - Spotify "tray" seems to show. But not as other icons in the "always visible" - it hides in the pop out menu. 

![image](https://github.com/flathub/com.spotify.Client/assets/11974489/7a9cff8c-5ad0-4400-b01b-9bea4e3fc959)

2023-10-22 12:20 UTC, Erick555 requested changes
It's not your fault but please remove `"branch": "stable",` from the manifest since this blocks installing test PR alongside stable app.

Also please add `require-important-update: true` in [flathub.json](https://github.com/flathub/com.spotify.Client/blob/master/flathub.json) and `is-main-source: true` into spotify x-checker metadata in order to prevent re-downloading whole spotify updates when some minor dep bumps version.

2023-10-22 12:20 UTC, Erick555 commented on com.spotify.Client.json
> +                    "name": "gtest",
this is build dep it should be cleanup up totally.

2023-10-23 19:25 UTC, slagiewka commented on com.spotify.Client.json
> +                    "name": "gtest",
You are right. Removed.

2023-10-23 19:31 UTC, slagiewka commented
> It's not your fault but please remove `"branch": "stable",` from the manifest since this blocks installing test PR alongside stable app.

Do you mean installing it locally (as per the test build output)? Actually I didn't find it annoying when the stable is installed and test is installed with `--user`. I just have to uninstall (with `--user`) when I want to install another build.

> Also please add `require-important-update: true` in [flathub.json](https://github.com/flathub/com.spotify.Client/blob/master/flathub.json) and `is-main-source: true` into spotify x-checker metadata in order to prevent re-downloading whole spotify when some minor dep bumps version.

This and the above suggestion seem like they should be done outside of this PR. And I personally wouldn't volunteer to touch these (at least not right now).

2023-10-23 20:26 UTC, Erick555 commented
> Do you mean installing it locally (as per the test build output)? Actually I didn't find it annoying when the stable is installed and test is installed with --user. I just have to uninstall (with --user) when I want to install another build.

What if stable is installed as --user as well? You need to remove it first to test anything.

2023-10-23 20:41 UTC, Erick555 commented
I made https://github.com/flathub/com.spotify.Client/pull/261 to speed-up things.

2023-10-24 00:00 UTC, merged